import{initializeApp}from"https://www.gstatic.com/firebasejs/11.4.0/firebase-app.js";import{getDatabase,ref,push,set,onValue,remove,update,runTransaction}from"https://www.gstatic.com/firebasejs/11.4.0/firebase-database.js";
const config={apiKey:"AIzaSyB-FX1wyTkycQ-21QRDf5VWy5p9N__ZNl8",authDomain:"inventario-app-dfead.firebaseapp.com",databaseURL:"https://inventario-app-dfead-default-rtdb.firebaseio.com",projectId:"inventario-app-dfead",storageBucket:"inventario-app-dfead.firebasestorage.app",messagingSenderId:"1012268791157",appId:"1:1012268791157:web:e2be525efa0cc13c318f3c"},db=getDatabase(initializeApp(config)),$=x=>document.getElementById(x),inv=ref(db,"inventario"),movRef=ref(db,"movimientos");let items=[],moves=[],edit=null,scanner,scanning=false;
const clean=(v,n=160)=>String(v??"").replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").trim().slice(0,n),valid=n=>Number.isInteger(Number(n))&&Number(n)>=0,cell=(tr,v,c)=>{let d=document.createElement("td");d.textContent=clean(v,500);if(c)d.className=c;tr.append(d);return d},btn=(t,c,f)=>{let b=document.createElement("button");b.type="button";b.textContent=t;b.className=c;b.onclick=f;return b},note=t=>{let d=document.createElement("div");d.textContent=t;d.style.cssText="position:fixed;right:20px;bottom:20px;background:#172033;color:#fff;padding:12px;border-radius:8px;z-index:200";document.body.append(d);setTimeout(()=>d.remove(),2200)};
async function log(x,t,q){await set(push(movRef),{timestamp:Date.now(),fechaHora:new Date().toISOString(),codigo:clean(x.codigo),nombre:clean(x.nombre),tipoAccion:t,cantidad:Number(q)||0})}
function filtered(){let q=clean($("search").value).toLowerCase();return items.filter(x=>([x.codigo,x.nombre,x.marca,x.modelo,x.categoria].join(" ").toLowerCase().includes(q))&&(!$("filterTipo").value||x.tipo===$("filterTipo").value)&&(!$("filterEstado").value||x.estado===$("filterEstado").value)&&(!$("filterCategoria").value||x.categoria===$("filterCategoria").value))}
function cats(){let old=$("filterCategoria").value,cs=[...new Set(items.map(x=>x.categoria).filter(Boolean))].sort();$("filterCategoria").replaceChildren(new Option("Todas las categorías",""),...cs.map(x=>new Option(clean(x),clean(x))));$("filterCategoria").value=cs.includes(old)?old:""}
function render(){cats();let b=$("body");b.replaceChildren();let a=filtered();if(!a.length){let tr=document.createElement("tr"),d=cell(tr,"No hay registros");d.colSpan=7;b.append(tr);return}a.forEach(x=>{let tr=document.createElement("tr");cell(tr,x.codigo);cell(tr,x.nombre);cell(tr,x.tipo);cell(tr,x.categoria);cell(tr,x.estado==="Asignado"?`${x.estado} · ${x.lugar||"Sin lugar"}`:`${x.estado} · ${x.bodega||"Sin ubicación"}`);let s=document.createElement("td"),g=document.createElement("div");g.className="stockCtl";g.append(btn("−","small secondary",()=>adjust(x,-1)),Object.assign(document.createElement("b"),{textContent:String(x.stock)}),btn("+","small",()=>adjust(x,1)));s.append(g);tr.append(s);let ac=document.createElement("td"),ag=document.createElement("div");ag.className="actions";ag.append(btn("Editar","secondary",()=>startEdit(x)),btn("Eliminar","danger",()=>del(x)));ac.append(ag);tr.append(ac);b.append(tr)})}
function alerts(){let a=items.filter(x=>x.stock<=x.minimo),b=$("alerts");$("alertCount").textContent=a.length;b.replaceChildren();if(!a.length){let tr=document.createElement("tr"),d=cell(tr,"No hay alertas");d.colSpan=5;b.append(tr);return}a.forEach(x=>{let tr=document.createElement("tr");cell(tr,x.codigo);cell(tr,x.nombre);cell(tr,x.stock,"critical");cell(tr,x.minimo);cell(tr,Math.max(1,x.minimo-x.stock+1));b.append(tr)})}
function history(){let b=$("moves");b.replaceChildren();moves.sort((a,b)=>b.timestamp-a.timestamp).forEach(x=>{let tr=document.createElement("tr");cell(tr,new Date(x.timestamp).toLocaleString("es-CO"));cell(tr,x.codigo);cell(tr,x.nombre);cell(tr,x.tipoAccion);cell(tr,x.cantidad);b.append(tr)})}
async function adjust(x,d){try{let r=await runTransaction(ref(db,`inventario/${x.idFirebase}/stock`),v=>{v=Number(v)||0;return d<0&&v===0?v:v+d});if(!r.committed)return;let n=Number(r.snapshot.val())||0;if(d<0&&x.stock<=0){note("El stock no puede ser negativo");return}await log({...x,stock:n},d>0?"Entrada (+1)":"Salida (-1)",d);note("Stock actualizado")}catch(e){console.error(e);note("Error al actualizar")}}
function dynamic(){let a=$("estado").value==="Asignado";$("bodegaWrap").hidden=a;$("lugarWrap").hidden=!a;$("responsableWrap").hidden=!a}
async function save(e){e.preventDefault();if(!valid($("stock").value)||!valid($("minimo").value)){note("Stock y mínimo deben ser enteros no negativos");return}let x={tipo:clean($("tipo").value),nombre:clean($("nombre").value),categoria:clean($("categoria").value),marca:clean($("marca").value),modelo:clean($("modelo").value),codigo:clean($("codigo").value,100),estado:clean($("estado").value),bodega:clean($("bodega").value),lugar:clean($("lugar").value),responsable:clean($("responsable").value),stock:Number($("stock").value),minimo:Number($("minimo").value),unidad:clean($("unidad").value,30),updatedAt:Date.now()};if(!x.nombre||!x.codigo||!x.categoria)return note("Completa los campos obligatorios");try{if(edit){await update(ref(db,`inventario/${edit}`),x);await log(x,"Edición",x.stock)}else{let k=push(inv);await set(k,{...x,createdAt:Date.now()});await log(x,"Registro",x.stock)}reset();note("Guardado")}catch(err){console.error(err);note("Error de Firebase")}}
function startEdit(x){edit=x.idFirebase;$("formTitle").textContent="Editar ítem";for(let [id,k] of Object.entries({tipo:"tipo",nombre:"nombre",categoria:"categoria",marca:"marca",modelo:"modelo",codigo:"codigo",estado:"estado",bodega:"bodega",lugar:"lugar",responsable:"responsable",stock:"stock",minimo:"minimo",unidad:"unidad"}))$(id).value=x[k]??"";$("cancel").hidden=false;dynamic()}
function reset(){$("itemForm").reset();edit=null;$("formTitle").textContent="Registrar ítem";$("stock").value=0;$("minimo").value=0;$("unidad").value="Unidad";$("cancel").hidden=true;dynamic()}
async function del(x){if(!confirm("¿Eliminar este registro?"))return;await remove(ref(db,`inventario/${x.idFirebase}`));await log(x,"Eliminación",x.stock)}
function sku(){let c=clean($("categoria").value).toUpperCase()||"OTROS",n=items.filter(x=>clean(x.categoria).toUpperCase()===c).length+1;$("codigo").value=`${c.slice(0,8)}-${String(n).padStart(3,"0")}`}
function beep(){try{let C=window.AudioContext||webkitAudioContext,c=new C,o=c.createOscillator(),g=c.createGain();o.frequency.value=880;g.gain.value=.08;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.12);o.onended=()=>c.close()}catch{}}
async function stopScan(){scanning=false;if(scanner){try{await scanner.stop()}catch{}try{await scanner.clear()}catch{}scanner=null}$("scannerModal").hidden=true}
async function openScan(){if(!window.Html5Qrcode)return note("Lector no disponible");$("scannerModal").hidden=false;scanner=new Html5Qrcode("reader");try{await scanner.start({facingMode:"environment"},{fps:10,qrbox:{width:260,height:180}},async t=>{if(scanning)return;scanning=true;$("codigo").value=clean(t,100);beep();await stopScan();note("Código detectado")},()=>{})}catch(e){note("No fue posible abrir la cámara");await stopScan()}}
function buildOrder(){let a=items.filter(x=>x.stock<=x.minimo),b=$("orderBody");$("folio").textContent="OR-"+String(Date.now()).slice(-6);$("fecha").textContent=new Date().toLocaleDateString("es-CO");b.replaceChildren();a.forEach((x,i)=>{let tr=document.createElement("tr");cell(tr,i+1);cell(tr,x.nombre);cell(tr,x.stock,"critical");cell(tr,x.minimo);cell(tr,Math.max(1,x.minimo-x.stock+1));b.append(tr)});if(!a.length){let tr=document.createElement("tr"),d=cell(tr,"No existen ítems críticos");d.colSpan=5;b.append(tr)}}
function openOrder(){buildOrder();$("orderModal").hidden=false}
function closeOrder(){$("orderModal").hidden=true}
function excel(){let d=filtered().map(x=>({Código:clean(x.codigo),Nombre:clean(x.nombre),Tipo:x.tipo,Categoría:x.categoria,Estado:x.estado,Stock:x.stock,Mínimo:x.minimo})),ws=XLSX.utils.json_to_sheet(d),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Inventario");XLSX.writeFile(wb,"inventario.xlsx")}
function pdf(){html2pdf().set({filename:"inventario.pdf",margin:8,jsPDF:{format:"a4",orientation:"landscape"}}).from(document.querySelector("#inventario .wrap")).save()}
function orderPDF(){html2pdf().set({filename:"orden-requerimiento.pdf",margin:8,jsPDF:{format:"a4"}}).from($("sheet")).save()}
function word(){let {Document,Packer,Paragraph}=docx,rows=items.filter(x=>x.stock<=x.minimo).map((x,i)=>new Paragraph(`${i+1}. ${clean(x.nombre)} | Actual: ${x.stock} | Mínimo: ${x.minimo}`)),d=new Document({sections:[{children:[new Paragraph({text:"SISTEMA DE GESTIÓN DE INVENTARIO",heading:"Heading1"}),new Paragraph("ORDEN DE REQUERIMIENTO"),...rows,new Paragraph("Justificación: Reposición de insumos críticos.")]}]});Packer.toBlob(d).then(b=>saveAs(b,"orden-requerimiento.docx"))}
$("itemForm").onsubmit=save;$("cancel").onclick=reset;$("estado").onchange=dynamic;$("sku").onclick=sku;$("scan").onclick=openScan;$("closeScan").onclick=stopScan;$("scannerModal").onclick=e=>{if(e.target===$("scannerModal"))stopScan()};$("order").onclick=openOrder;$("closeOrder").onclick=closeOrder;$("orderModal").onclick=e=>{if(e.target===$("orderModal"))closeOrder()};$("orderPdf").onclick=orderPDF;$("orderWord").onclick=word;$("excel").onclick=excel;$("pdf").onclick=pdf;["search","filterTipo","filterEstado","filterCategoria"].forEach(id=>$(id).addEventListener(id==="search"?"input":"change",render));document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab,.panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.tab).classList.add("active")});document.onkeydown=e=>{if(e.key==="Escape"){stopScan();closeOrder()}};
onValue(inv,s=>{items=Object.entries(s.val()||{}).map(([id,x])=>({idFirebase:id,...x}));render();alerts();$("sync").textContent="Sincronizado en tiempo real"});onValue(movRef,s=>{moves=Object.values(s.val()||{});history()});dynamic();